from dotenv import load_dotenv
load_dotenv()

import base64
import hashlib
import hmac
import json
import os
import re
import textwrap
from contextlib import closing
from datetime import date, datetime
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

try:
    import bcrypt
    BCRYPT_AVAILABLE = True
except ModuleNotFoundError:
    bcrypt = None
    BCRYPT_AVAILABLE = False

try:
    import psycopg2
    from psycopg2.extras import DictCursor
    DB_CONNECTOR_AVAILABLE = True
    DBIntegrityError = psycopg2.IntegrityError
except ModuleNotFoundError:
    psycopg2 = None
    DictCursor = None
    DB_CONNECTOR_AVAILABLE = False
    DBIntegrityError = Exception

BASE_DIR = Path(__file__).resolve().parent / "static"
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
PASSWORD_RECOVERY_KEY = os.environ.get('PASSWORD_RECOVERY_KEY', '').strip()
JWT_SECRET = os.environ.get('JWT_SECRET', '').strip() or PASSWORD_RECOVERY_KEY or 'change-this-jwt-secret'
JWT_EXP_SECONDS = int(os.environ.get('JWT_EXP_SECONDS', '28800'))
ROLE_WEIGHT = {'user': 1, 'admin': 2, 'general_admin': 3, 'master_admin': 4}
PERMISSIONS = {
    'master_admin': {'dashboard:view', 'users:view', 'users:create', 'users:update', 'users:delete', 'units:view', 'units:create', 'units:update', 'units:delete', 'employees:view', 'employees:create', 'employees:update', 'employees:delete', 'epis:view', 'epis:create', 'epis:update', 'epis:delete', 'deliveries:view', 'deliveries:create', 'fichas:view', 'reports:view', 'alerts:view', 'companies:view', 'companies:create', 'companies:update', 'companies:license', 'commercial:view', 'usage:view'},
    'general_admin': {'dashboard:view', 'users:view', 'users:create', 'users:update', 'units:view', 'units:create', 'units:update', 'units:delete', 'employees:view', 'employees:create', 'employees:update', 'employees:delete', 'epis:view', 'epis:create', 'epis:update', 'epis:delete', 'deliveries:view', 'deliveries:create', 'fichas:view', 'reports:view', 'alerts:view', 'companies:view'},
    'admin': {'dashboard:view', 'users:view', 'users:create', 'users:update', 'units:view', 'units:create', 'units:update', 'units:delete', 'employees:view', 'employees:create', 'employees:update', 'employees:delete', 'epis:view', 'epis:create', 'epis:update', 'epis:delete', 'deliveries:view', 'deliveries:create', 'fichas:view', 'reports:view', 'alerts:view'},
    'user': {'dashboard:view', 'deliveries:view', 'deliveries:create', 'fichas:view', 'alerts:view', 'units:view', 'employees:view', 'epis:view'}
}


class PostgresCursorWrapper:
    def __init__(self, cursor, inserted_id=None):
        self._cursor = cursor
        self.lastrowid = inserted_id

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class PostgresConnectionWrapper:
    def __init__(self, connection):
        self._connection = connection

    def _normalize_sql(self, query):
        normalized = str(query)
        normalized = normalized.replace('INTEGER PRIMARY KEY AUTOINCREMENT', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        normalized = normalized.replace('?', '%s')
        return normalized

    def execute(self, query, params=None):
        sql = self._normalize_sql(query)
        cursor = self._connection.cursor(cursor_factory=DictCursor)
        inserted_id = None
        if sql.lstrip().upper().startswith('INSERT INTO ') and ' RETURNING ' not in sql.upper():
            sql = sql.rstrip().rstrip(';') + ' RETURNING id'
            cursor.execute(sql, params or ())
            row = cursor.fetchone()
            inserted_id = row[0] if row else None
        else:
            cursor.execute(sql, params or ())
        return PostgresCursorWrapper(cursor, inserted_id)

    def executemany(self, query, seq_of_params):
        sql = self._normalize_sql(query)
        with self._connection.cursor() as cursor:
            cursor.executemany(sql, seq_of_params)

    def executescript(self, script):
        statements = [item.strip() for item in str(script).split(';') if item.strip()]
        with self._connection.cursor() as cursor:
            for statement in statements:
                cursor.execute(self._normalize_sql(statement))

    def cursor(self):
        return self._connection.cursor(cursor_factory=DictCursor)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()

    def __getattr__(self, name):
        return getattr(self._connection, name)


def get_connection():
    if not DB_CONNECTOR_AVAILABLE:
        raise RuntimeError('Instale psycopg2-binary para usar o servidor Postgres/Supabase.')
    if not DATABASE_URL:
        raise RuntimeError('DATABASE_URL nao configurada.')
    raw_connection = psycopg2.connect(DATABASE_URL)
    return PostgresConnectionWrapper(raw_connection)


def row_to_dict(row):
    return {key: row[key] for key in row.keys()}


def _json_safe(value):
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    return str(value)


def structured_log(level, event, **fields):
    payload = {
        'ts': datetime.utcnow().isoformat() + 'Z',
        'level': str(level).lower(),
        'event': event,
        **{key: _json_safe(value) for key, value in fields.items()}
    }
    print(json.dumps(payload, ensure_ascii=False), flush=True)


def send_json(handler, status, payload):
    body = json.dumps(payload, ensure_ascii=False).encode('utf-8')
    handler.send_response(status)
    handler.send_header('Content-Type', 'application/json; charset=utf-8')
    handler.send_header('Content-Length', str(len(body)))
    handler.end_headers()
    handler.wfile.write(body)
    if str(handler.path).startswith('/api/') or str(handler.path).startswith('/health'):
        structured_log(
            'info' if status < 400 else 'error',
            'http.response',
            method=getattr(handler, 'command', ''),
            path=getattr(handler, 'path', ''),
            status=status
        )


def send_bytes(handler, status, content_type, body, filename=None):
    handler.send_response(status)
    handler.send_header('Content-Type', content_type)
    handler.send_header('Content-Length', str(len(body)))
    if filename:
        handler.send_header('Content-Disposition', f'attachment; filename="{filename}"')
    handler.end_headers()
    handler.wfile.write(body)


def parse_json(handler):
    length = int(handler.headers.get('Content-Length', '0'))
    raw = handler.rfile.read(length) if length else b'{}'
    return json.loads(raw.decode('utf-8'))


def require_fields(payload, fields):
    for field in fields:
        if payload.get(field) in (None, ''):
            raise ValueError(f'Campo obrigatório: {field}')

def validate_password_strength(password):
    raw = str(password or '').strip()
    if len(raw) < 6:
        raise ValueError('A senha deve ter pelo menos 6 caracteres.')
    return raw


def jwt_b64encode(data_bytes):
    return base64.urlsafe_b64encode(data_bytes).decode('utf-8').rstrip('=')


def jwt_b64decode(data):
    raw = str(data or '')
    padding = '=' * (-len(raw) % 4)
    return base64.urlsafe_b64decode((raw + padding).encode('utf-8'))


def create_jwt_token(user_row):
    now_ts = int(datetime.utcnow().timestamp())
    payload = {
        'sub': int(user_row['id']),
        'role': user_row['role'],
        'company_id': user_row['company_id'],
        'iat': now_ts,
        'exp': now_ts + JWT_EXP_SECONDS
    }
    header_segment = jwt_b64encode(json.dumps({'alg': 'HS256', 'typ': 'JWT'}, separators=(',', ':')).encode('utf-8'))
    payload_segment = jwt_b64encode(json.dumps(payload, separators=(',', ':')).encode('utf-8'))
    signing_input = f'{header_segment}.{payload_segment}'.encode('utf-8')
    signature = hmac.new(JWT_SECRET.encode('utf-8'), signing_input, hashlib.sha256).digest()
    signature_segment = jwt_b64encode(signature)
    return f'{header_segment}.{payload_segment}.{signature_segment}'


def parse_bearer_token(handler):
    auth_header = str(handler.headers.get('Authorization', '')).strip()
    if not auth_header:
        return ''
    if not auth_header.lower().startswith('bearer '):
        raise PermissionError('Formato de Authorization inválido.')
    return auth_header.split(' ', 1)[1].strip()


def decode_jwt_token(token):
    raw = str(token or '').strip()
    if not raw:
        raise PermissionError('Token ausente.')
    parts = raw.split('.')
    if len(parts) != 3:
        raise PermissionError('Token inválido.')
    header_segment, payload_segment, signature_segment = parts
    signing_input = f'{header_segment}.{payload_segment}'.encode('utf-8')
    expected_signature = hmac.new(JWT_SECRET.encode('utf-8'), signing_input, hashlib.sha256).digest()
    provided_signature = jwt_b64decode(signature_segment)
    if not hmac.compare_digest(expected_signature, provided_signature):
        raise PermissionError('Token inválido.')
    try:
        payload = json.loads(jwt_b64decode(payload_segment).decode('utf-8'))
    except (ValueError, json.JSONDecodeError):
        raise PermissionError('Token inválido.')
    if int(payload.get('exp', 0)) < int(datetime.utcnow().timestamp()):
        raise PermissionError('Sessão expirada. Faça login novamente.')
    return payload


def resolve_actor_user_id(handler, parsed, payload=None):
    payload = payload or {}
    query_actor = parse_qs(parsed.query).get('actor_user_id', [''])[0]
    body_actor = str(payload.get('actor_user_id', '')).strip()
    token = parse_bearer_token(handler)
    token_actor = ''
    if token:
        claims = decode_jwt_token(token)
        token_actor = str(claims.get('sub', '')).strip()
    actor_candidates = [item for item in (body_actor, query_actor, token_actor) if str(item).strip()]
    if not actor_candidates:
        raise PermissionError('Sessão inválida: usuário não informado.')
    actor_user_id = actor_candidates[0]
    for candidate in actor_candidates[1:]:
        if str(candidate) != str(actor_user_id):
            raise PermissionError('Dados de autenticação inconsistentes.')
    return int(actor_user_id)


def is_bcrypt_hash(value):
    raw = str(value or '')
    return raw.startswith('$2a$') or raw.startswith('$2b$') or raw.startswith('$2y$')


def hash_password(password):
    raw = validate_password_strength(password)
    if not BCRYPT_AVAILABLE:
        return raw
    return bcrypt.hashpw(raw.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')


def verify_password(stored_password, provided_password):
    stored = str(stored_password or '')
    provided = str(provided_password or '')
    if is_bcrypt_hash(stored):
        if not BCRYPT_AVAILABLE:
            return False
        return bcrypt.checkpw(provided.encode('utf-8'), stored.encode('utf-8'))
    return stored == provided


def only_digits(value):
    return ''.join(ch for ch in str(value or '') if ch.isdigit())


def normalize_unit_type(value):
    raw = str(value or '').strip().lower()
    aliases = {
        'navio': 'embarcacao',
        'embarcação': 'embarcacao',
        'embarcacao': 'embarcacao',
        'base': 'base',
        'plataforma': 'plataforma',
    }
    return aliases.get(raw, raw or 'base')


def format_cnpj(value):
    digits = only_digits(value)
    if len(digits) != 14:
        return str(value or '').strip()
    return f"{digits[:2]}.{digits[2:5]}.{digits[5:8]}/{digits[8:12]}-{digits[12:]}"


def is_valid_cnpj(value):
    digits = only_digits(value)
    if len(digits) != 14 or len(set(digits)) == 1:
        return False

    numbers = [int(item) for item in digits]
    weights_one = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]
    total = sum(number * weight for number, weight in zip(numbers[:12], weights_one))
    remainder = total % 11
    digit_one = 0 if remainder < 2 else 11 - remainder

    weights_two = [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]
    total = sum(number * weight for number, weight in zip(numbers[:12] + [digit_one], weights_two))
    remainder = total % 11
    digit_two = 0 if remainder < 2 else 11 - remainder
    return numbers[12] == digit_one and numbers[13] == digit_two


def validate_cnpj(value):
    if not is_valid_cnpj(value):
        raise ValueError('CNPJ inválido.')
    return format_cnpj(value)


def ensure_unique_company_cnpj(connection, cnpj, exclude_company_id=None):
    normalized = only_digits(cnpj)
    rows = connection.execute('SELECT id, cnpj FROM companies').fetchall()
    for row in rows:
        if exclude_company_id and int(row['id']) == int(exclude_company_id):
            continue
        if only_digits(row['cnpj']) == normalized:
            raise ValueError('Já existe uma empresa cadastrada com este CNPJ.')


def validate_logo_payload(value):
    logo = str(value or '').strip()
    if not logo:
        return ''
    if logo.startswith('data:image/'):
        allowed = ('data:image/png', 'data:image/jpeg', 'data:image/jpg', 'data:image/svg+xml')
        if not logo.startswith(allowed):
            raise ValueError('Logotipo inválido. Envie PNG, JPG ou SVG.')
    return logo


def validate_company_payload(connection, payload, company_id=None):
    settings = get_commercial_settings(connection)
    payload['name'] = str(payload.get('name', '')).strip()
    payload['legal_name'] = str(payload.get('legal_name', '')).strip()
    payload['cnpj'] = validate_cnpj(payload.get('cnpj', ''))
    ensure_unique_company_cnpj(connection, payload['cnpj'], company_id)
    payload['logo_type'] = validate_logo_payload(payload.get('logo_type', ''))
    payload['plan_name'] = normalize_plan_key(payload.get('plan_name') or 'start')
    if payload['plan_name'] not in settings['plans']:
        raise ValueError('Plano comercial invalido.')
    payload['commercial_notes'] = str(payload.get('commercial_notes', '')).strip()
    payload['user_limit'] = int(payload.get('user_limit', 0))
    if payload['user_limit'] < 1:
        raise ValueError('O limite de usuarios deve ser maior que zero.')
    payload['addendum_enabled'] = 1 if str(payload.get('addendum_enabled', '0')).lower() in ('1', 'true', 'on', 'yes') else 0
    plan = settings['plans'][payload['plan_name']]
    if payload['user_limit'] < plan['min_users']:
        raise ValueError(f"O plano {plan['label']} exige no minimo {plan['min_users']} usuario(s).")
    if plan['max_users'] is not None and payload['user_limit'] > plan['max_users'] and not payload['addendum_enabled']:
        raise ValueError(f"O plano {plan['label']} permite ate {plan['max_users']} usuarios sem aditivo contratual.")
    active_users = count_company_users(connection, company_id) if company_id else 0
    if active_users > payload['user_limit']:
        raise ValueError('O limite contratado nao pode ficar abaixo da quantidade atual de usuarios ativos.')
    payload['monthly_value'] = round(active_users * float(settings['unit_price']), 2)
    payload['contract_start'] = str(payload.get('contract_start', '')).strip()
    payload['contract_end'] = str(payload.get('contract_end', '')).strip()
    if payload['contract_start']:
        datetime.strptime(payload['contract_start'], '%Y-%m-%d')
    if payload['contract_end']:
        datetime.strptime(payload['contract_end'], '%Y-%m-%d')
    if payload['contract_start'] and payload['contract_end'] and payload['contract_end'] < payload['contract_start']:
        raise ValueError('A data final do contrato deve ser maior ou igual a data inicial.')
    payload['license_status'] = str(payload.get('license_status', 'active')).strip() or 'active'
    payload['unit_price'] = float(settings['unit_price'])
    payload['projected_monthly_value'] = round(payload['user_limit'] * payload['unit_price'], 2)
    return payload


def bad_request(handler, message):
    send_json(handler, 400, {'error': message})


def forbidden(handler, message):
    send_json(handler, 403, {'error': message})


def not_found(handler):
    send_json(handler, 404, {'error': 'Rota não encontrada.'})


INITIAL_MASTER_ADMIN = {'username': 'admin', 'password': 'admin123', 'full_name': 'Administrador Master'}
DEFAULT_PLATFORM_BRAND = {'display_name': 'Sua Empresa', 'legal_name': '', 'cnpj': '', 'logo_type': ''}
DEFAULT_COMMERCIAL_SETTINGS = {
    'unit_price': 42.0,
    'plans': {
        'individual': {'label': 'Individual', 'min_users': 1, 'max_users': 1},
        'start': {'label': 'Start', 'min_users': 1, 'max_users': 10},
        'business': {'label': 'Business', 'min_users': 11, 'max_users': 25},
        'corporate': {'label': 'Corporate', 'min_users': 26, 'max_users': 100},
        'enterprise': {'label': 'Enterprise', 'min_users': 101, 'max_users': None},
    },
}


def default_commercial_settings():
    return json.loads(json.dumps(DEFAULT_COMMERCIAL_SETTINGS))


def normalize_plan_key(value):
    normalized = str(value or '').strip().lower()
    aliases = {
        'individual': 'individual',
        'indivudual': 'individual',
        'start': 'start',
        'business': 'business',
        'corporate': 'corporate',
        'enterprise': 'enterprise',
    }
    return aliases.get(normalized, normalized)


def ensure_commercial_settings(connection):
    if not get_meta(connection, 'commercial_settings'):
        set_meta(connection, 'commercial_settings', json.dumps(default_commercial_settings(), ensure_ascii=False))


def get_commercial_settings(connection):
    settings = default_commercial_settings()
    raw = get_meta(connection, 'commercial_settings')
    if not raw:
        return settings
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        return settings
    settings['unit_price'] = float(parsed.get('unit_price', settings['unit_price']) or settings['unit_price'])
    for key, plan in settings['plans'].items():
        source = (parsed.get('plans') or {}).get(key, {})
        plan['label'] = str(source.get('label', plan['label'])).strip() or plan['label']
        plan['min_users'] = max(1, int(source.get('min_users', plan['min_users']) or plan['min_users']))
        raw_max = source.get('max_users', plan['max_users'])
        plan['max_users'] = None if raw_max in (None, '', 'null') else max(plan['min_users'], int(raw_max))
    return settings


def save_commercial_settings(connection, payload):
    actor = require_master_actor(connection, int(payload.get('actor_user_id') or 0))
    current = get_commercial_settings(connection)
    unit_price = float(str(payload.get('unit_price', current['unit_price'])).replace(',', '.'))
    if unit_price <= 0:
        raise ValueError('O valor unitario precisa ser maior que zero.')
    plans_payload = payload.get('plans') or {}
    settings = default_commercial_settings()
    settings['unit_price'] = unit_price
    details = [{'field': 'Valor unitario', 'before': str(current['unit_price']), 'after': str(unit_price)}]
    for key, default_plan in settings['plans'].items():
        current_plan = current['plans'][key]
        source = plans_payload.get(key) or current_plan
        label = str(source.get('label', default_plan['label'])).strip() or default_plan['label']
        min_users = max(1, int(source.get('min_users', default_plan['min_users']) or default_plan['min_users']))
        raw_max = source.get('max_users', default_plan['max_users'])
        max_users = None if raw_max in (None, '', 'null') else max(min_users, int(raw_max))
        settings['plans'][key] = {'label': label, 'min_users': min_users, 'max_users': max_users}
        details.append({
            'field': f'Plano {label}',
            'before': f"min {current_plan['min_users']} / max {current_plan['max_users'] if current_plan['max_users'] is not None else 'livre'}",
            'after': f"min {min_users} / max {max_users if max_users is not None else 'livre'}"
        })
    if settings['plans']['individual']['max_users'] < 1:
        raise ValueError('O plano Individual precisa permitir pelo menos 1 usuario.')
    if settings['plans']['start']['max_users'] < settings['plans']['individual']['max_users']:
        raise ValueError('O limite do plano Start nao pode ser menor que o Individual.')
    if settings['plans']['business']['min_users'] > settings['plans']['business']['max_users']:
        raise ValueError('O plano Business esta com faixa invalida.')
    if settings['plans']['corporate']['min_users'] > settings['plans']['corporate']['max_users']:
        raise ValueError('O plano Corporate esta com faixa invalida.')
    if settings['plans']['enterprise']['min_users'] <= settings['plans']['corporate']['max_users']:
        raise ValueError('O plano Enterprise precisa comecar acima do limite do Corporate.')
    set_meta(connection, 'commercial_settings', json.dumps(settings, ensure_ascii=False))
    return actor, settings, details


def commercial_plan_for_company(company, settings):
    return settings['plans'].get(normalize_plan_key(company.get('plan_name')))


def compute_company_contract_metrics(company, settings):
    active_users = int(company.get('user_count') or 0)
    user_limit = int(company.get('user_limit') or 0)
    unit_price = float(settings['unit_price'])
    addendum_enabled = int(company.get('addendum_enabled') or 0)
    plan = commercial_plan_for_company(company, settings)
    min_users = plan['min_users'] if plan else 1
    max_users = plan['max_users'] if plan else None
    return {
        'unit_price': unit_price,
        'calculated_monthly_value': round(active_users * unit_price, 2),
        'projected_monthly_value': round(user_limit * unit_price, 2),
        'plan_min_users': min_users,
        'plan_max_users': max_users,
        'requires_addendum': bool(plan and max_users is not None and user_limit > max_users),
        'within_plan_limit': bool(plan and user_limit >= min_users and (max_users is None or user_limit <= max_users)),
        'addendum_enabled': addendum_enabled,
    }



def get_platform_brand(connection):
    raw = get_meta(connection, 'platform_brand')
    if not raw:
        return dict(DEFAULT_PLATFORM_BRAND)
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        return dict(DEFAULT_PLATFORM_BRAND)
    return {**DEFAULT_PLATFORM_BRAND, **parsed}


def validate_platform_brand_payload(payload):
    brand = {
        'display_name': str(payload.get('display_name', '')).strip() or DEFAULT_PLATFORM_BRAND['display_name'],
        'legal_name': str(payload.get('legal_name', '')).strip(),
        'cnpj': str(payload.get('cnpj', '')).strip(),
        'logo_type': validate_logo_payload(payload.get('logo_type', ''))
    }
    if brand['cnpj']:
        brand['cnpj'] = validate_cnpj(brand['cnpj'])
    return brand


def save_platform_brand(connection, payload):
    brand = validate_platform_brand_payload(payload)
    set_meta(connection, 'platform_brand', json.dumps(brand, ensure_ascii=False))
    return brand


def require_master_actor(connection, actor_user_id):
    actor = authorize_action(connection, actor_user_id, 'commercial:view')
    if actor['role'] != 'master_admin':
        raise PermissionError('Apenas o Administrador Master pode alterar a marca do sistema.')
    return actor


def get_meta(connection, key):
    with connection.cursor() as cursor:
        cursor.execute(
            'SELECT value FROM app_meta WHERE key = %s',
            (key,)
        )
        row = cursor.fetchone()
        return row['value'] if row else None


def set_meta(connection, key, value):
    with connection.cursor() as cursor:
        cursor.execute(
            '''
            INSERT INTO app_meta (key, value)
            VALUES (%s, %s)
            ON CONFLICT (key)
            DO UPDATE SET value = EXCLUDED.value
            ''',
            (key, value)
        )


def migrate_role_hierarchy(connection):
    connection.execute("UPDATE users SET role = 'master_admin', company_id = NULL WHERE role = 'general_admin' AND company_id IS NULL")



def ensure_company_columns(connection):
    migrations = [
        "ALTER TABLE companies ADD COLUMN IF NOT EXISTS legal_name TEXT NOT NULL DEFAULT ''",
        "ALTER TABLE companies ADD COLUMN IF NOT EXISTS plan_name TEXT NOT NULL DEFAULT 'Plano padrao'",
        "ALTER TABLE companies ADD COLUMN IF NOT EXISTS user_limit INTEGER NOT NULL DEFAULT 25",
        "ALTER TABLE companies ADD COLUMN IF NOT EXISTS license_status TEXT NOT NULL DEFAULT 'active'",
        "ALTER TABLE companies ADD COLUMN IF NOT EXISTS active INTEGER NOT NULL DEFAULT 1",
        "ALTER TABLE companies ADD COLUMN IF NOT EXISTS commercial_notes TEXT NOT NULL DEFAULT ''",
        "ALTER TABLE companies ADD COLUMN IF NOT EXISTS contract_start TEXT NOT NULL DEFAULT ''",
        "ALTER TABLE companies ADD COLUMN IF NOT EXISTS contract_end TEXT NOT NULL DEFAULT ''",
        "ALTER TABLE companies ADD COLUMN IF NOT EXISTS monthly_value REAL NOT NULL DEFAULT 0",
        "ALTER TABLE companies ADD COLUMN IF NOT EXISTS addendum_enabled INTEGER NOT NULL DEFAULT 0",
    ]
    for sql in migrations:
        connection.execute(sql)



def company_license_label(status):
    return {
        'active': 'Ativo',
        'trial': 'Trial',
        'suspended': 'Suspenso',
        'expired': 'Expirado',
    }.get(status, status)


def count_company_users(connection, company_id):
    return connection.execute("SELECT COUNT(*) FROM users WHERE company_id = ? AND active = 1", (company_id,)).fetchone()[0]


def ensure_company_user_limit(connection, company_id, ignore_user_id=None):
    company = connection.execute('SELECT id, name, user_limit, active, license_status FROM companies WHERE id = ?', (company_id,)).fetchone()
    if not company:
        raise ValueError('Empresa não encontrada.')
    if not int(company['active']) or company['license_status'] in ('suspended', 'expired'):
        raise ValueError('Empresa sem licença ativa para novos usuários.')
    contract_end = connection.execute('SELECT contract_end FROM companies WHERE id = ?', (company_id,)).fetchone()['contract_end']
    if contract_end and contract_end < date.today().isoformat():
        raise ValueError('Contrato expirado para novos usuários.')
    query = 'SELECT COUNT(*) FROM users WHERE company_id = ? AND active = 1'
    params = [company_id]
    if ignore_user_id:
        query += ' AND id != ?'
        params.append(ignore_user_id)
    active_users = connection.execute(query, tuple(params)).fetchone()[0]
    if active_users >= int(company['user_limit']):
        raise ValueError('Limite de usuários contratado atingido para esta empresa.')


def get_company_by_id(connection, company_id):
    row = connection.execute(
        'SELECT id, name, user_limit, license_status, active, contract_end, addendum_enabled FROM companies WHERE id = ?',
        (company_id,)
    ).fetchone()
    return row_to_dict(row) if row else None


def enforce_company_block_rules(connection, company_id):
    status = evaluate_company_block_status(connection, company_id, persist_expiration=True)
    if not status['blocked']:
        return
    reason_priority = status['reasons'][0]
    if reason_priority == 'company_inactive':
        raise PermissionError('Acesso bloqueado: empresa inativa.')
    if reason_priority in ('license_suspended', 'license_expired_by_contract'):
        raise PermissionError('Acesso bloqueado: licença suspensa ou expirada.')
    if reason_priority == 'usage_exceeds_contract':
        raise PermissionError('Acesso bloqueado: uso acima do limite contratado.')
    raise PermissionError('Acesso bloqueado por política comercial.')


def evaluate_company_block_status(connection, company_id, persist_expiration=True):
    company = get_company_by_id(connection, company_id)
    if not company:
        raise ValueError('Empresa vinculada não encontrada.')

    reasons = []
    today_iso = date.today().isoformat()
    contract_end = str(company.get('contract_end') or '').strip()
    license_status = str(company.get('license_status') or 'active').strip() or 'active'
    if contract_end and contract_end < today_iso:
        reasons.append('license_expired_by_contract')
        if persist_expiration and license_status != 'expired':
            connection.execute('UPDATE companies SET license_status = ? WHERE id = ?', ('expired', company_id))
            connection.commit()
            license_status = 'expired'
    if int(company.get('active') or 0) != 1:
        reasons.append('company_inactive')
    if license_status == 'suspended':
        reasons.append('license_suspended')
    if license_status == 'expired':
        reasons.append('license_expired_by_contract')
    active_users = count_company_users(connection, company_id)
    user_limit = int(company.get('user_limit') or 0)
    addendum_enabled = int(company.get('addendum_enabled') or 0) == 1
    if user_limit > 0 and active_users > user_limit and not addendum_enabled:
        reasons.append('usage_exceeds_contract')

    dedup_reasons = []
    for reason in reasons:
        if reason not in dedup_reasons:
            dedup_reasons.append(reason)
    return {
        'company_id': int(company_id),
        'blocked': bool(dedup_reasons),
        'reasons': dedup_reasons,
        'license_status': license_status,
        'active_users': active_users,
        'user_limit': user_limit,
        'addendum_enabled': addendum_enabled,
        'contract_end': contract_end,
    }

def ensure_initial_master_admin(connection):
    admin_user = connection.execute("SELECT id, username, full_name, password FROM users WHERE username = ? LIMIT 1", (INITIAL_MASTER_ADMIN['username'],)).fetchone()
    if admin_user:
        password_to_store = admin_user['password']
        if not is_bcrypt_hash(password_to_store):
            password_to_store = hash_password(password_to_store)
        connection.execute(
            "UPDATE users SET password = ?, full_name = ?, role = 'master_admin', company_id = NULL, active = 1 WHERE id = ?",
            (password_to_store, INITIAL_MASTER_ADMIN['full_name'], admin_user['id'])
        )
        set_meta(connection, 'initial_master_admin_bootstrapped', str(admin_user['id']))
        return {'id': admin_user['id'], **INITIAL_MASTER_ADMIN}

    cursor = connection.execute(
        'INSERT INTO users (username, password, full_name, role, company_id, active) VALUES (?, ?, ?, ?, ?, ?)',
        (INITIAL_MASTER_ADMIN['username'], hash_password(INITIAL_MASTER_ADMIN['password']), INITIAL_MASTER_ADMIN['full_name'], 'master_admin', None, 1)
    )
    set_meta(connection, 'initial_master_admin_bootstrapped', str(cursor.lastrowid))
    return {'id': cursor.lastrowid, **INITIAL_MASTER_ADMIN}


def init_db():
    with closing(get_connection()) as connection:
        connection.executescript(
            '''
            CREATE TABLE IF NOT EXISTS companies (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL UNIQUE,
                legal_name TEXT NOT NULL DEFAULT '',
                cnpj TEXT NOT NULL UNIQUE,
                logo_type TEXT NOT NULL,
                plan_name TEXT NOT NULL DEFAULT 'Plano padrão',
                user_limit INTEGER NOT NULL DEFAULT 25,
                license_status TEXT NOT NULL DEFAULT 'active',
                active INTEGER NOT NULL DEFAULT 1,
                commercial_notes TEXT NOT NULL DEFAULT '',
                contract_start TEXT NOT NULL DEFAULT '',
                contract_end TEXT NOT NULL DEFAULT '',
                monthly_value REAL NOT NULL DEFAULT 0,
                addendum_enabled INTEGER NOT NULL DEFAULT 0
            );
            CREATE TABLE IF NOT EXISTS app_meta (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT NOT NULL UNIQUE,
                password TEXT NOT NULL,
                full_name TEXT NOT NULL,
                role TEXT NOT NULL,
                company_id INTEGER,
                active INTEGER NOT NULL DEFAULT 1,
                FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL
            );
            CREATE TABLE IF NOT EXISTS company_audit_logs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                company_id INTEGER NOT NULL,
                actor_user_id INTEGER NOT NULL,
                actor_name TEXT NOT NULL,
                action_type TEXT NOT NULL,
                summary TEXT NOT NULL,
                details_json TEXT NOT NULL DEFAULT '[]',
                created_at TEXT NOT NULL,
                FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
                FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE RESTRICT
            );
            CREATE TABLE IF NOT EXISTS units (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                company_id INTEGER NOT NULL,
                name TEXT NOT NULL,
                unit_type TEXT NOT NULL,
                city TEXT NOT NULL,
                notes TEXT DEFAULT '',
                UNIQUE(company_id, name),
                FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT
            );
            CREATE TABLE IF NOT EXISTS employees (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                company_id INTEGER NOT NULL,
                unit_id INTEGER NOT NULL,
                employee_id_code TEXT NOT NULL UNIQUE,
                name TEXT NOT NULL,
                sector TEXT NOT NULL,
                role_name TEXT NOT NULL,
                admission_date TEXT NOT NULL,
                schedule_type TEXT NOT NULL,
                FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT,
                FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT
            );
            CREATE TABLE IF NOT EXISTS epis (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                company_id INTEGER NOT NULL,
                unit_id INTEGER,
                name TEXT NOT NULL,
                purchase_code TEXT NOT NULL,
                ca TEXT NOT NULL,
                sector TEXT NOT NULL,
                stock INTEGER NOT NULL DEFAULT 0,
                unit_measure TEXT NOT NULL,
                ca_expiry TEXT NOT NULL,
                epi_validity_date TEXT NOT NULL,
                manufacture_date TEXT NOT NULL,
                validity_days INTEGER NOT NULL,
                qr_code_value TEXT,
                UNIQUE(company_id, purchase_code),
                UNIQUE(company_id, ca),
                UNIQUE(company_id, qr_code_value),
                FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT,
                FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT
            );
            CREATE TABLE IF NOT EXISTS deliveries (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                company_id INTEGER NOT NULL,
                employee_id INTEGER NOT NULL,
                epi_id INTEGER NOT NULL,
                quantity INTEGER NOT NULL,
                quantity_label TEXT NOT NULL,
                sector TEXT NOT NULL,
                role_name TEXT NOT NULL,
                delivery_date TEXT NOT NULL,
                next_replacement_date TEXT NOT NULL,
                notes TEXT DEFAULT '',
                signature_name TEXT NOT NULL,
                FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE RESTRICT,
                FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE RESTRICT,
                FOREIGN KEY (epi_id) REFERENCES epis(id) ON DELETE RESTRICT
            );
            CREATE TABLE IF NOT EXISTS employee_unit_movements (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                employee_id INTEGER NOT NULL,
                company_id INTEGER NOT NULL,
                source_unit_id INTEGER NOT NULL,
                target_unit_id INTEGER NOT NULL,
                movement_type TEXT NOT NULL,
                start_date TEXT NOT NULL,
                end_date TEXT NOT NULL DEFAULT '',
                notes TEXT NOT NULL DEFAULT '',
                actor_user_id INTEGER NOT NULL,
                actor_name TEXT NOT NULL,
                created_at TEXT NOT NULL,
                FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
                FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
                FOREIGN KEY (source_unit_id) REFERENCES units(id) ON DELETE RESTRICT,
                FOREIGN KEY (target_unit_id) REFERENCES units(id) ON DELETE RESTRICT,
                FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE RESTRICT
            );
            '''
        )
        ensure_company_columns(connection)
        ensure_company_audit_columns(connection)
        ensure_epi_columns(connection)
        ensure_commercial_settings(connection)
        if connection.execute('SELECT COUNT(*) FROM companies').fetchone()[0] == 0:
            connection.executemany('INSERT INTO companies (name, legal_name, cnpj, logo_type, plan_name, user_limit, license_status, active, commercial_notes, contract_start, contract_end, monthly_value, addendum_enabled) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [('DOF Brasil', 'DOF Subsea Brasil Servicos Ltda', '11.222.333/0001-81', '', 'enterprise', 120, 'active', 1, 'Contrato corporativo ativo.', '2026-01-01', '2026-12-31', 0.0, 0), ('Norskan Offshore', 'Norskan Offshore Ltda', '44.555.666/0001-81', '', 'corporate', 80, 'active', 1, 'Operacao offshore ativa.', '2026-01-01', '2026-12-31', 0.0, 0)])
        companies = {row['name']: row['id'] for row in connection.execute('SELECT id, name FROM companies').fetchall()}
        connection.execute("UPDATE companies SET cnpj = '11.222.333/0001-81', contract_start = COALESCE(NULLIF(contract_start, ''), '2026-01-01'), contract_end = COALESCE(NULLIF(contract_end, ''), '2026-12-31'), plan_name = CASE WHEN plan_name IN ('Plano padrao', 'Plano padrão', 'Enterprise Offshore') THEN 'enterprise' ELSE plan_name END, logo_type = COALESCE(logo_type, ''), addendum_enabled = COALESCE(addendum_enabled, 0) WHERE name = 'DOF Brasil'")
        connection.execute("UPDATE companies SET cnpj = '44.555.666/0001-81', contract_start = COALESCE(NULLIF(contract_start, ''), '2026-01-01'), contract_end = COALESCE(NULLIF(contract_end, ''), '2026-12-31'), plan_name = CASE WHEN plan_name IN ('Plano padrao', 'Plano padrão', 'Fleet Base') THEN 'corporate' ELSE plan_name END, logo_type = COALESCE(logo_type, ''), addendum_enabled = COALESCE(addendum_enabled, 0) WHERE name = 'Norskan Offshore'")
        connection.execute("UPDATE units SET unit_type = 'embarcacao' WHERE unit_type IN ('navio', 'embarcação')")
        migrate_role_hierarchy(connection)
        existing_usernames = {row['username'] for row in connection.execute('SELECT username FROM users').fetchall()}
        users_to_insert = []
        if 'dof.general' not in existing_usernames:
            users_to_insert.append(('dof.general', hash_password('dofgeneral123'), 'Administrador Geral DOF Brasil', 'general_admin', companies['DOF Brasil']))
        if 'dof.admin' not in existing_usernames:
            users_to_insert.append(('dof.admin', hash_password('dofadmin123'), 'Administrador DOF Brasil', 'admin', companies['DOF Brasil']))
        if 'dof.user' not in existing_usernames:
            users_to_insert.append(('dof.user', hash_password('dof123'), 'Usuário DOF Brasil', 'user', companies['DOF Brasil']))
        if 'norskan.general' not in existing_usernames:
            users_to_insert.append(('norskan.general', hash_password('norskangeneral123'), 'Administrador Geral Norskan', 'general_admin', companies['Norskan Offshore']))
        if 'norskan.admin' not in existing_usernames:
            users_to_insert.append(('norskan.admin', hash_password('norskanadmin123'), 'Administrador Norskan', 'admin', companies['Norskan Offshore']))
        if 'norskan.user' not in existing_usernames:
            users_to_insert.append(('norskan.user', hash_password('norskan123'), 'Usuário Norskan Offshore', 'user', companies['Norskan Offshore']))
        if users_to_insert:
            connection.executemany('INSERT INTO users (username, password, full_name, role, company_id) VALUES (?, ?, ?, ?, ?)', users_to_insert)
        bootstrap_admin = ensure_initial_master_admin(connection)
        if connection.execute('SELECT COUNT(*) FROM units').fetchone()[0] == 0:
            connection.executemany('INSERT INTO units (company_id, name, unit_type, city, notes) VALUES (?, ?, ?, ?, ?)', [(companies['DOF Brasil'], 'Base Macae', 'base', 'Macae', 'Base onshore'), (companies['DOF Brasil'], 'Navio Skandi', 'navio', 'Bacia de Campos', 'Navio offshore'), (companies['Norskan Offshore'], 'Base Rio Capital', 'base', 'Rio de Janeiro', 'Base onshore'), (companies['Norskan Offshore'], 'Navio Norskan Alpha', 'navio', 'Bacia de Santos', 'Navio offshore')])
        if connection.execute('SELECT COUNT(*) FROM employees').fetchone()[0] == 0:
            dof_base = connection.execute("SELECT id FROM units WHERE name = 'Base Macae'").fetchone()['id']
            norskan_ship = connection.execute("SELECT id FROM units WHERE name = 'Navio Norskan Alpha'").fetchone()['id']
            connection.executemany('INSERT INTO employees (company_id, unit_id, employee_id_code, name, sector, role_name, admission_date, schedule_type) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', [(companies['DOF Brasil'], dof_base, '1001', 'Carlos Souza', 'Producao', 'Operador', '2025-01-10', '14x14'), (companies['Norskan Offshore'], norskan_ship, '2001', 'Fernanda Lima', 'SSMA', 'Tecnica de Seguranca', '2024-11-20', '28x28')])
        if connection.execute('SELECT COUNT(*) FROM epis').fetchone()[0] == 0:
            dof_base = connection.execute("SELECT id FROM units WHERE name = 'Base Macae'").fetchone()['id']
            norskan_ship = connection.execute("SELECT id FROM units WHERE name = 'Navio Norskan Alpha'").fetchone()['id']
            connection.executemany('INSERT INTO epis (company_id, unit_id, name, purchase_code, ca, sector, stock, unit_measure, ca_expiry, epi_validity_date, manufacture_date, validity_days, qr_code_value) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [(companies['DOF Brasil'], dof_base, 'Capacete Classe B', 'COD-001', '12345', 'Producao', 18, 'unidade', '2026-04-25', '2026-10-25', '2025-10-25', 180, f"EPI-{companies['DOF Brasil']}-{dof_base}-COD-001"), (companies['DOF Brasil'], dof_base, 'Bota de Seguranca', 'COD-002', '12346', 'Producao', 12, 'par', '2026-08-01', '2027-02-01', '2025-08-01', 180, f"EPI-{companies['DOF Brasil']}-{dof_base}-COD-002"), (companies['Norskan Offshore'], norskan_ship, 'Luva Nitrilica', 'COD-101', '67890', 'SSMA', 7, 'par', '2026-03-28', '2026-09-28', '2025-09-28', 60, f"EPI-{companies['Norskan Offshore']}-{norskan_ship}-COD-101")])
        connection.execute("UPDATE epis SET unit_id = COALESCE(unit_id, (SELECT id FROM units WHERE units.company_id = epis.company_id ORDER BY id LIMIT 1)) WHERE unit_id IS NULL")
        connection.execute("UPDATE epis SET qr_code_value = COALESCE(NULLIF(qr_code_value, ''), 'EPI-' || company_id || '-' || COALESCE(unit_id, 0) || '-' || UPPER(REPLACE(purchase_code, ' ', '-')))")
        connection.commit()
        return bootstrap_admin


def ensure_company_audit_columns(connection):
    connection.execute("ALTER TABLE company_audit_logs ADD COLUMN IF NOT EXISTS details_json TEXT NOT NULL DEFAULT '[]'")


def ensure_epi_columns(connection):
    connection.execute("ALTER TABLE epis ADD COLUMN IF NOT EXISTS unit_id INTEGER")
    connection.execute("ALTER TABLE epis ADD COLUMN IF NOT EXISTS qr_code_value TEXT")


def generate_epi_qr_code(payload):
    purchase_code = str(payload.get('purchase_code', '')).strip().upper().replace(' ', '-')
    return f"EPI-{payload.get('company_id')}-{payload.get('unit_id')}-{purchase_code}"


def company_action_label(action_type):
    return {
        'create': 'Criação',
        'update': 'Atualização',
        'suspend': 'Suspensão',
        'reactivate': 'Reativação',
    }.get(action_type, action_type)


def summarize_company_changes(previous, payload):
    tracked_fields = {
        'plan_name': 'Plano',
        'user_limit': 'Limite de usuários',
        'license_status': 'Status da licença',
        'active': 'Status da empresa',
        'contract_start': 'Início do contrato',
        'contract_end': 'Fim do contrato',
        'monthly_value': 'Valor mensal atual',
        'addendum_enabled': 'Aditivo contratual',
        'commercial_notes': 'Observações',
    }
    if not previous:
        details = [{
            'field': tracked_fields[field],
            'before': '',
            'after': str(payload.get(field, ''))
        } for field in tracked_fields]
        return f"Empresa criada com plano {payload['plan_name']} e limite de {payload['user_limit']} usuários.", details
    changes = []
    details = []
    for field, label in tracked_fields.items():
        previous_value = str(previous.get(field, ''))
        current_value = str(payload.get(field, ''))
        if previous_value != current_value:
            changes.append(label.lower())
            details.append({'field': label, 'before': previous_value, 'after': current_value})
    summary = 'Alteração em ' + ', '.join(changes) + '.' if changes else 'Dados comerciais revisados sem mudança crítica.'
    return summary, details


def register_company_audit(connection, company_id, actor, action_type, summary, details=None):
    connection.execute(
        'INSERT INTO company_audit_logs (company_id, actor_user_id, actor_name, action_type, summary, details_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)',
        (company_id, actor['id'], actor['full_name'], action_type, summary, json.dumps(details or [], ensure_ascii=False), datetime.now().isoformat(timespec='seconds')),
    )


def fetch_company_audit_logs(connection, actor=None):
    sql = """SELECT company_audit_logs.id, company_audit_logs.company_id, company_audit_logs.actor_user_id, company_audit_logs.actor_name,
                    company_audit_logs.action_type, company_audit_logs.summary, company_audit_logs.details_json, company_audit_logs.created_at,
                    companies.name AS company_name
             FROM company_audit_logs
             JOIN companies ON companies.id = company_audit_logs.company_id"""
    if actor and actor['role'] != 'master_admin':
        rows = connection.execute(sql + ' WHERE company_audit_logs.company_id = ? ORDER BY company_audit_logs.created_at DESC, company_audit_logs.id DESC', (actor['company_id'],)).fetchall()
    else:
        rows = connection.execute(sql + ' ORDER BY company_audit_logs.created_at DESC, company_audit_logs.id DESC').fetchall()
    logs = []
    for row in rows:
        item = row_to_dict(row)
        item['action_label'] = company_action_label(item['action_type'])
        item['details'] = json.loads(item.get('details_json') or '[]')
        logs.append(item)
    return logs


def pdf_safe_text(value):
    text = str(value or '')
    text = text.encode('cp1252', 'replace').decode('cp1252')
    return text.replace('\\', '\\\\').replace('(', '\\(').replace(')', '\\)')


def extract_jpeg_dimensions(image_bytes):
    if not image_bytes.startswith(b'\xff\xd8'):
        raise ValueError('JPEG inválido.')
    offset = 2
    sof_markers = {0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF}
    standalone_markers = {0x01, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9}

    while offset < len(image_bytes):
        while offset < len(image_bytes) and image_bytes[offset] != 0xFF:
            offset += 1
        while offset < len(image_bytes) and image_bytes[offset] == 0xFF:
            offset += 1
        if offset >= len(image_bytes):
            break

        marker_byte = image_bytes[offset]
        offset += 1

        if marker_byte in standalone_markers:
            continue
        if offset + 2 > len(image_bytes):
            break

        segment_length = int.from_bytes(image_bytes[offset:offset + 2], 'big')
        if segment_length < 2 or offset + segment_length > len(image_bytes):
            break

        if marker_byte in sof_markers:
            segment_start = offset + 2
            if segment_start + 5 > len(image_bytes):
                break
            height = int.from_bytes(image_bytes[segment_start + 1:segment_start + 3], 'big')
            width = int.from_bytes(image_bytes[segment_start + 3:segment_start + 5], 'big')
            if width > 0 and height > 0:
                return width, height

        offset += segment_length

    return 1, 1


def extract_pdf_logo_image(data_uri):
    value = str(data_uri or '')
    if not value.startswith('data:image/jpeg;base64,') and not value.startswith('data:image/jpg;base64,'):
        return None
    image_bytes = base64.b64decode(value.split(',', 1)[1])
    width, height = extract_jpeg_dimensions(image_bytes)
    return {'bytes': image_bytes, 'width': width, 'height': height}


def build_pdf_document(page_lines, header_image=None):
    objects = []

    def add_object(content):
        objects.append(content)
        return len(objects)

    catalog_id = add_object('')
    pages_id = add_object('')
    font_regular_id = add_object('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>')
    font_bold_id = add_object('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>')
    image_object_id = None
    if header_image:
        image_stream = header_image['bytes']
        image_object_id = add_object(
            f"<< /Type /XObject /Subtype /Image /Width {header_image['width']} /Height {header_image['height']} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length {len(image_stream)} >>\nstream\n".encode('latin-1')
            + image_stream
            + b"\nendstream"
        )
    page_ids = []
    for lines in page_lines:
        commands = ['q 0.96 0.85 0.78 rg 40 770 515 44 re f Q']
        if image_object_id:
            commands.append('q 72 0 0 36 452 774 cm /Im1 Do Q')
        for line in lines:
            font = '/F2' if line.get('bold') else '/F1'
            size = line.get('size', 12)
            x = line.get('x', 50)
            y = line.get('y', 760)
            commands.append(f"BT {font} {size} Tf 1 0 0 1 {x} {y} Tm ({pdf_safe_text(line.get('text', ''))}) Tj ET")
        content_stream = '\n'.join(commands).encode('cp1252', 'replace')
        content_id = add_object(f"<< /Length {len(content_stream)} >>\nstream\n".encode('latin-1') + content_stream + b"\nendstream")
        image_resource = f" /XObject << /Im1 {image_object_id} 0 R >>" if image_object_id else ''
        page_id = add_object(f"<< /Type /Page /Parent {pages_id} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 {font_regular_id} 0 R /F2 {font_bold_id} 0 R >>{image_resource} >> /Contents {content_id} 0 R >>")
        page_ids.append(page_id)
    kids = ' '.join(f'{page_id} 0 R' for page_id in page_ids)
    objects[pages_id - 1] = f"<< /Type /Pages /Count {len(page_ids)} /Kids [{kids}] >>"
    objects[catalog_id - 1] = f"<< /Type /Catalog /Pages {pages_id} 0 R >>"

    output = bytearray(b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n')
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(output))
        if isinstance(obj, bytes):
            output.extend(f"{index} 0 obj\n".encode('latin-1'))
            output.extend(obj)
            output.extend(b"\nendobj\n")
        else:
            output.extend(f"{index} 0 obj\n{obj}\nendobj\n".encode('latin-1'))
    xref_pos = len(output)
    output.extend(f"xref\n0 {len(objects) + 1}\n".encode('latin-1'))
    output.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.extend(f"{offset:010d} 00000 n \n".encode('latin-1'))
    output.extend(f"trailer\n<< /Size {len(objects) + 1} /Root {catalog_id} 0 R >>\nstartxref\n{xref_pos}\n%%EOF".encode('latin-1'))
    return bytes(output)


def build_commercial_contract_pdf(connection, actor, company_id):
    ensure_company_access(actor, company_id)
    company = connection.execute('SELECT * FROM companies WHERE id = ?', (company_id,)).fetchone()
    if not company:
        raise ValueError('Empresa nao encontrada.')
    company = row_to_dict(company)
    company['user_count'] = count_company_users(connection, company_id)
    settings = get_commercial_settings(connection)
    metrics = compute_company_contract_metrics(company, settings)
    brand = get_platform_brand(connection)
    logo_image = extract_pdf_logo_image(brand.get('logo_type'))
    today = datetime.now()
    monthly_value = f"R$ {float(metrics['calculated_monthly_value'] or 0):,.2f}".replace(',', 'X').replace('.', ',').replace('X', '.')
    projected_value = f"R$ {float(metrics['projected_monthly_value'] or 0):,.2f}".replace(',', 'X').replace('.', ',').replace('X', '.')
    unit_price = f"R$ {float(metrics['unit_price'] or 0):,.2f}".replace(',', 'X').replace('.', ',').replace('X', '.')
    pages = []
    page_lines = []
    y = 792

    def add_line(text_value, size=12, bold=False, x=52, gap=18):
        nonlocal y, page_lines
        if y < 70:
            pages.append(page_lines)
            page_lines = []
            y = 792
        page_lines.append({'text': text_value, 'size': size, 'bold': bold, 'x': x, 'y': y})
        y -= gap

    add_line(brand.get('display_name') or 'Sua Empresa', size=22, bold=True, x=52, gap=28)
    if brand.get('legal_name'):
        add_line(brand['legal_name'], size=11, x=52, gap=16)
    if brand.get('cnpj'):
        add_line(f"CNPJ: {brand['cnpj']}", size=11, x=52, gap=20)
    add_line('Contrato Comercial de Licenca do Sistema', size=18, bold=True, x=52, gap=24)
    add_line(f"Gerado em {today.strftime('%d/%m/%Y %H:%M')}", size=10, x=52, gap=22)
    add_line('Empresa contratante', size=14, bold=True, x=52, gap=20)
    add_line(company['name'], size=12, bold=True, x=52, gap=18)
    add_line(f"Razao social: {company.get('legal_name') or '-'}")
    add_line(f"CNPJ: {company.get('cnpj') or '-'}")
    add_line(f"Plano contratado: {company.get('plan_name') or '-'}")
    add_line(f"Usuarios ativos: {company.get('user_count') or 0}")
    add_line(f"Limite de usuarios ativos: {company.get('user_limit') or 0}")
    add_line(f"Valor unitario: {unit_price}")
    add_line(f"Valor mensal atual: {monthly_value}")
    add_line(f"Valor projetado pelo limite contratado: {projected_value}")
    add_line(f"Status da licenca: {company_license_label(company.get('license_status'))}")
    add_line(f"Status da empresa: {'Ativa' if int(company.get('active') or 0) == 1 else 'Inativa'}")
    add_line(f"Aditivo contratual: {'Sim' if int(company.get('addendum_enabled') or 0) == 1 else 'Nao'}")
    add_line(f"Inicio do contrato: {company.get('contract_start') or '-'}")
    add_line(f"Fim do contrato: {company.get('contract_end') or '-'}")
    add_line('Observacoes comerciais', size=14, bold=True, x=52, gap=20)
    notes = company.get('commercial_notes') or 'Sem observacoes comerciais registradas.'
    for wrapped in textwrap.wrap(notes, width=82):
        add_line(wrapped, size=11, x=52, gap=16)
    add_line('Clausulas operacionais', size=14, bold=True, x=52, gap=20)
    clauses = [
        '1. O valor mensal atual e calculado automaticamente pela quantidade de usuarios ativos.',
        '2. O valor unitario e definido pelo Administrador Master no modulo comercial.',
        '3. Ao atingir o limite contratado, novos usuarios ativos serao bloqueados.',
        '4. Exceder o plano padrao exige aditivo contratual ativo.',
    ]
    for clause in clauses:
        for wrapped in textwrap.wrap(clause, width=82):
            add_line(wrapped, size=11, x=52, gap=16)
    add_line('Assinaturas', size=14, bold=True, x=52, gap=22)
    add_line(f"Contratada: {brand.get('display_name') or 'Sua Empresa'}", size=11, x=52, gap=40)
    add_line(f"Contratante: {company['name']}", size=11, x=52, gap=40)
    pages.append(page_lines)
    return build_pdf_document(pages, logo_image)


def fetch_companies(connection, company_id=None):
    settings = get_commercial_settings(connection)
    sql = '''SELECT companies.id, companies.name, companies.legal_name, companies.cnpj, companies.logo_type, companies.plan_name, companies.user_limit, companies.license_status, companies.active, companies.commercial_notes, companies.contract_start, companies.contract_end, companies.monthly_value, companies.addendum_enabled, COUNT(users.id) AS user_count FROM companies LEFT JOIN users ON users.company_id = companies.id AND users.active = 1'''
    if company_id:
        rows = connection.execute(sql + ' WHERE companies.id = ? GROUP BY companies.id ORDER BY companies.name', (company_id,)).fetchall()
    else:
        rows = connection.execute(sql + ' GROUP BY companies.id ORDER BY companies.name').fetchall()
    companies = []
    for row in rows:
        item = row_to_dict(row)
        metrics = compute_company_contract_metrics(item, settings)
        item.update(metrics)
        item['monthly_value'] = metrics['calculated_monthly_value']
        item['license_status_label'] = company_license_label(item['license_status'])
        item['limit_reached'] = int(item['user_count']) >= int(item['user_limit'])
        item['available_slots'] = max(int(item['user_limit']) - int(item['user_count']), 0)
        item['near_limit'] = int(item['user_limit']) > 0 and (int(item['user_count']) / int(item['user_limit'])) >= 0.8
        companies.append(item)
    return companies


def fetch_users(connection, actor=None):
    if actor and actor['role'] == 'user':
        return []
    sql = '''SELECT users.id, users.username, users.full_name, users.role, users.company_id, users.active, companies.name AS company_name, companies.cnpj AS company_cnpj, companies.logo_type FROM users LEFT JOIN companies ON companies.id = users.company_id'''
    order_by = " ORDER BY CASE users.role WHEN 'master_admin' THEN 4 WHEN 'general_admin' THEN 3 WHEN 'admin' THEN 2 ELSE 1 END DESC, users.full_name"
    if actor and actor['role'] in ('general_admin', 'admin'):
        rows = connection.execute(sql + " WHERE users.company_id = ? OR users.id = ?" + order_by, (actor['company_id'], actor['id'])).fetchall()
    else:
        rows = connection.execute(sql + order_by).fetchall()
    return [row_to_dict(row) for row in rows]

def fetch_units(connection, actor=None):
    sql = '''SELECT units.id, units.company_id, units.name, units.unit_type, units.city, units.notes, companies.name AS company_name, companies.cnpj AS company_cnpj, companies.logo_type FROM units JOIN companies ON companies.id = units.company_id'''
    if actor and actor['role'] != 'master_admin':
        rows = connection.execute(sql + ' WHERE units.company_id = ? ORDER BY companies.name, units.name', (actor['company_id'],)).fetchall()
    else:
        rows = connection.execute(sql + ' ORDER BY companies.name, units.name').fetchall()
    return [row_to_dict(row) for row in rows]


def fetch_employees(connection, actor=None):
    sql = '''SELECT employees.id, employees.company_id, employees.unit_id, employees.employee_id_code, employees.name, employees.sector, employees.role_name, employees.admission_date, employees.schedule_type, companies.name AS company_name, companies.cnpj AS company_cnpj, companies.logo_type, units.name AS unit_name, units.unit_type, units.city AS unit_city FROM employees JOIN companies ON companies.id = employees.company_id JOIN units ON units.id = employees.unit_id'''
    if actor and actor['role'] != 'master_admin':
        rows = connection.execute(sql + ' WHERE employees.company_id = ? ORDER BY employees.name', (actor['company_id'],)).fetchall()
    else:
        rows = connection.execute(sql + ' ORDER BY employees.name').fetchall()
    employees = [row_to_dict(row) for row in rows]
    today_iso = date.today().isoformat()
    for employee in employees:
        movement = connection.execute(
            '''
            SELECT employee_unit_movements.target_unit_id, units.name AS target_unit_name, units.unit_type AS target_unit_type
            FROM employee_unit_movements
            JOIN units ON units.id = employee_unit_movements.target_unit_id
            WHERE employee_unit_movements.employee_id = ?
              AND employee_unit_movements.movement_type = 'temporary'
              AND employee_unit_movements.start_date <= ?
              AND COALESCE(NULLIF(employee_unit_movements.end_date, ''), '9999-12-31') >= ?
            ORDER BY employee_unit_movements.start_date DESC, employee_unit_movements.id DESC
            LIMIT 1
            ''',
            (employee['id'], today_iso, today_iso)
        ).fetchone()
        if movement:
            employee['current_unit_id'] = movement['target_unit_id']
            employee['current_unit_name'] = movement['target_unit_name']
            employee['current_unit_type'] = movement['target_unit_type']
            employee['unit_allocation_type'] = 'temporary'
        else:
            employee['current_unit_id'] = employee['unit_id']
            employee['current_unit_name'] = employee['unit_name']
            employee['current_unit_type'] = employee['unit_type']
            employee['unit_allocation_type'] = 'primary'
    return employees


def fetch_employee_movements(connection, actor=None):
    sql = '''
    SELECT employee_unit_movements.id, employee_unit_movements.employee_id, employee_unit_movements.company_id,
           employee_unit_movements.source_unit_id, employee_unit_movements.target_unit_id, employee_unit_movements.movement_type,
           employee_unit_movements.start_date, employee_unit_movements.end_date, employee_unit_movements.notes,
           employee_unit_movements.actor_user_id, employee_unit_movements.actor_name, employee_unit_movements.created_at,
           employees.name AS employee_name, employees.employee_id_code,
           source_units.name AS source_unit_name, target_units.name AS target_unit_name
    FROM employee_unit_movements
    JOIN employees ON employees.id = employee_unit_movements.employee_id
    JOIN units AS source_units ON source_units.id = employee_unit_movements.source_unit_id
    JOIN units AS target_units ON target_units.id = employee_unit_movements.target_unit_id
    '''
    if actor and actor['role'] != 'master_admin':
        rows = connection.execute(sql + ' WHERE employee_unit_movements.company_id = ? ORDER BY employee_unit_movements.created_at DESC, employee_unit_movements.id DESC', (actor['company_id'],)).fetchall()
    else:
        rows = connection.execute(sql + ' ORDER BY employee_unit_movements.created_at DESC, employee_unit_movements.id DESC').fetchall()
    return [row_to_dict(row) for row in rows]


def fetch_epis(connection, actor=None):
    sql = '''SELECT epis.id, epis.company_id, epis.unit_id, epis.name, epis.purchase_code, epis.ca, epis.sector, epis.stock, epis.unit_measure, epis.ca_expiry, epis.epi_validity_date, epis.manufacture_date, epis.validity_days, epis.qr_code_value, companies.name AS company_name, companies.cnpj AS company_cnpj, companies.logo_type, units.name AS unit_name, units.unit_type FROM epis JOIN companies ON companies.id = epis.company_id LEFT JOIN units ON units.id = epis.unit_id'''
    if actor and actor['role'] != 'master_admin':
        rows = connection.execute(sql + ' WHERE epis.company_id = ? ORDER BY companies.name, epis.name', (actor['company_id'],)).fetchall()
    else:
        rows = connection.execute(sql + ' ORDER BY companies.name, epis.name').fetchall()
    return [row_to_dict(row) for row in rows]


def fetch_deliveries(connection, actor=None, where_clause='', params=()):
    clauses = []
    query_params = list(params)
    if actor and actor['role'] != 'master_admin':
        clauses.append('deliveries.company_id = ?')
        query_params.append(actor['company_id'])
    if where_clause:
        clean = where_clause.strip()
        clauses.append(clean[6:] if clean.upper().startswith('WHERE ') else clean)
    final_where = f"WHERE {' AND '.join(clauses)}" if clauses else ''
    rows = connection.execute(f'''SELECT deliveries.id, deliveries.company_id, deliveries.employee_id, deliveries.epi_id, deliveries.quantity, deliveries.quantity_label, deliveries.sector, deliveries.role_name, deliveries.delivery_date, deliveries.next_replacement_date, deliveries.notes, deliveries.signature_name, companies.name AS company_name, companies.cnpj AS company_cnpj, companies.logo_type, employees.employee_id_code, employees.name AS employee_name, employees.schedule_type, units.name AS unit_name, units.unit_type, epis.name AS epi_name, epis.purchase_code, epis.ca, epis.unit_measure, epis.epi_validity_date, epis.manufacture_date, epis.qr_code_value FROM deliveries JOIN companies ON companies.id = deliveries.company_id JOIN employees ON employees.id = deliveries.employee_id JOIN units ON units.id = employees.unit_id JOIN epis ON epis.id = deliveries.epi_id {final_where} ORDER BY deliveries.delivery_date DESC, deliveries.id DESC''', tuple(query_params)).fetchall()
    return [row_to_dict(row) for row in rows]


def compute_alerts(connection, actor=None):
    alerts = []
    today = date.today()
    for epi in fetch_epis(connection, actor):
        days = (datetime.strptime(epi['ca_expiry'], '%Y-%m-%d').date() - today).days
        stock = int(epi['stock'])
        if stock <= 10:
            alerts.append({'type': 'danger' if stock <= 5 else 'warning', 'title': f"Estoque baixo: {epi['name']}", 'description': f"{epi['company_name']} - saldo atual de {stock} {epi['unit_measure']}(s)."})
        if days <= 30:
            alerts.append({'type': 'danger' if days <= 7 else 'warning', 'title': f"CA próximo do vencimento: {epi['name']}", 'description': f"{epi['company_name']} - vence em {epi['ca_expiry']}."})
    return alerts


def get_user_by_id(connection, user_id):
    row = connection.execute('SELECT users.id, users.username, users.password, users.full_name, users.role, users.company_id, users.active, companies.name AS company_name, companies.cnpj AS company_cnpj, companies.logo_type FROM users LEFT JOIN companies ON companies.id = users.company_id WHERE users.id = ?', (user_id,)).fetchone()
    return row_to_dict(row) if row else None


def get_unit_by_id(connection, unit_id):
    row = connection.execute('SELECT id, company_id, name, unit_type, city, notes FROM units WHERE id = ?', (unit_id,)).fetchone()
    return row_to_dict(row) if row else None


def get_employee_by_id(connection, employee_id):
    row = connection.execute('SELECT id, company_id, unit_id, employee_id_code, name, sector, role_name, admission_date, schedule_type FROM employees WHERE id = ?', (employee_id,)).fetchone()
    return row_to_dict(row) if row else None


def get_epi_by_id(connection, epi_id):
    row = connection.execute('SELECT id, company_id, unit_id, name, purchase_code, ca, sector, stock, unit_measure, ca_expiry, epi_validity_date, manufacture_date, validity_days, qr_code_value FROM epis WHERE id = ?', (epi_id,)).fetchone()
    return row_to_dict(row) if row else None


def require_actor(connection, actor_user_id):
    actor = get_user_by_id(connection, int(actor_user_id))
    if not actor or not int(actor['active']):
        raise PermissionError('Usuário executor inválido.')
    if actor.get('role') != 'master_admin' and actor.get('company_id'):
        enforce_company_block_rules(connection, int(actor['company_id']))
    return actor


def ensure_permission(actor, action):
    if action not in PERMISSIONS.get(actor['role'], set()):
        raise PermissionError('Perfil sem permissão para esta ação.')


def ensure_company_access(actor, company_id):
    if actor['role'] == 'master_admin':
        return
    if str(actor.get('company_id') or '') != str(company_id or ''):
        raise PermissionError('Acesso permitido apenas para registros da prpria empresa.')


def ensure_resource_company(actor, resource, label='Registro'):
    if not resource:
        raise ValueError(f'{label} não encontrado.')
    ensure_company_access(actor, resource.get('company_id'))


def authorize_action(connection, actor_user_id, action, company_id=None):
    actor = require_actor(connection, actor_user_id)
    ensure_permission(actor, action)
    if company_id is not None:
        ensure_company_access(actor, company_id)
    return actor


def authorize_user_management(connection, actor_user_id, operation='create', target_role=None, target_user_id=None, target_company_id=None):
    action = {'create': 'users:create', 'update': 'users:update', 'delete': 'users:delete'}[operation]
    actor = authorize_action(connection, actor_user_id, action)
    target = get_user_by_id(connection, target_user_id) if target_user_id else None

    if target_user_id and not target:
        raise ValueError('Usuário alvo não encontrado.')

    if actor['role'] == 'master_admin':
        if target_role == 'master_admin' and target_user_id is None:
            raise ValueError('Não é permitido criar outro Administrador Master por esta tela.')
        if target and target['role'] == 'master_admin':
            if target['id'] == actor['id']:
                if operation == 'delete':
                    raise ValueError('Não é permitido excluir o próprio usuário logado.')
                if target_role and ROLE_WEIGHT.get(target_role, 0) < ROLE_WEIGHT['master_admin']:
                    raise ValueError('Administrador Master não pode remover a própria administração.')
            else:
                raise ValueError('Administrador Master s? pode ser gerenciado pelo bootstrap inicial do sistema.')
        return actor

    if actor['role'] == 'general_admin':
        if target_role and target_role not in ('admin', 'user'):
            raise ValueError('Administrador Geral pode gerenciar apenas Administradores e Usuários da própria empresa.')
        if target:
            if target['role'] not in ('admin', 'user'):
                raise ValueError('Administrador Geral pode alterar apenas Administradores e Usuários.')
            ensure_company_access(actor, target.get('company_id'))
        if target_company_id:
            ensure_company_access(actor, target_company_id)
        return actor

    if actor['role'] == 'admin':
        if target_role and target_role != 'user':
            raise ValueError('Administrador pode gerenciar apenas Usuários comuns.')
        if target:
            if target['role'] != 'user':
                raise ValueError('Administrador pode alterar apenas Usuários.')
            ensure_company_access(actor, target.get('company_id'))
        if target_company_id:
            ensure_company_access(actor, target_company_id)
        return actor

    raise PermissionError('Somente perfis administrativos podem gerenciar usuários.')


def parse_actor_user_id_from_query(parsed):
    return int(parse_qs(parsed.query).get('actor_user_id', ['0'])[0])


def build_reports(connection, actor, filters):
    clauses, params = [], []
    if filters.get('company_id'):
        ensure_company_access(actor, int(filters['company_id']))
        clauses.append('deliveries.company_id = ?')
        params.append(filters['company_id'])
    if filters.get('unit_id'):
        unit = get_unit_by_id(connection, int(filters['unit_id']))
        ensure_resource_company(actor, unit, 'Unidade')
        clauses.append('employees.unit_id = ?')
        params.append(filters['unit_id'])
    if filters.get('sector'):
        clauses.append('deliveries.sector = ?')
        params.append(filters['sector'])
    if filters.get('epi_id'):
        epi = get_epi_by_id(connection, int(filters['epi_id']))
        ensure_resource_company(actor, epi, 'EPI')
        clauses.append('deliveries.epi_id = ?')
        params.append(filters['epi_id'])
    if filters.get('start_date'):
        clauses.append('deliveries.delivery_date >= ?')
        params.append(filters['start_date'])
    if filters.get('end_date'):
        clauses.append('deliveries.delivery_date <= ?')
        params.append(filters['end_date'])
    where_clause = f"WHERE {' AND '.join(clauses)}" if clauses else ''
    deliveries = fetch_deliveries(connection, actor, where_clause, tuple(params))
    by_unit, by_sector, by_epi = {}, {}, {}
    for item in deliveries:
        by_unit[item['unit_name']] = by_unit.get(item['unit_name'], 0) + int(item['quantity'])
        by_sector[item['sector']] = by_sector.get(item['sector'], 0) + int(item['quantity'])
        by_epi[item['epi_name']] = by_epi.get(item['epi_name'], 0) + int(item['quantity'])
    return {'deliveries': deliveries, 'by_unit': by_unit, 'by_sector': by_sector, 'by_epi': by_epi, 'total_quantity': sum(int(item['quantity']) for item in deliveries)}


def build_bootstrap(connection, actor):
    return {'platform_brand': get_platform_brand(connection), 'commercial_settings': get_commercial_settings(connection), 'companies': fetch_companies(connection, None if actor['role'] == 'master_admin' else actor['company_id']), 'company_audit_logs': fetch_company_audit_logs(connection, actor), 'users': fetch_users(connection, actor), 'units': fetch_units(connection, actor), 'employees': fetch_employees(connection, actor), 'employee_movements': fetch_employee_movements(connection, actor), 'epis': fetch_epis(connection, actor), 'deliveries': fetch_deliveries(connection, actor), 'alerts': compute_alerts(connection, actor), 'permissions': sorted(PERMISSIONS.get(actor['role'], set()))}


def auth_diagnostics():
    parsed_db = urlparse(DATABASE_URL) if DATABASE_URL else None
    host = parsed_db.hostname if parsed_db else ''
    return {
        'database_configured': bool(DATABASE_URL),
        'database_host': host,
        'database_provider': 'supabase' if 'supabase' in str(host).lower() else 'custom_postgres',
        'db_connector_available': DB_CONNECTOR_AVAILABLE,
        'bcrypt_available': BCRYPT_AVAILABLE,
        'jwt_exp_seconds': JWT_EXP_SECONDS,
        'jwt_secret_default': JWT_SECRET == 'change-this-jwt-secret',
        'password_recovery_key_configured': bool(PASSWORD_RECOVERY_KEY)
    }


class EpiHandler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(BASE_DIR), **kwargs)

    def do_GET(self):
        parsed = urlparse(self.path)

        if parsed.path == '/health':
            return send_json(self, 200, {'status': 'ok'})

        if parsed.path == '/':
            self.path = '/index.html'
            return super().do_GET()

        try:
            if parsed.path == '/api/auth-diagnostics':
                return send_json(self, 200, auth_diagnostics())

            if parsed.path == '/api/bootstrap':
                with closing(get_connection()) as connection:
                    actor = authorize_action(
                        connection,
                        resolve_actor_user_id(self, parsed),
                        'dashboard:view'
                    )
                    return send_json(self, 200, build_bootstrap(connection, actor))

            if parsed.path == '/api/reports':
                with closing(get_connection()) as connection:
                    actor = authorize_action(
                        connection,
                        resolve_actor_user_id(self, parsed),
                        'reports:view'
                    )
                    filters = {
                        key: values[0]
                        for key, values in parse_qs(parsed.query).items()
                        if key != 'actor_user_id'
                    }
                    return send_json(self, 200, build_reports(connection, actor, filters))

            return super().do_GET()

        except PermissionError as exc:
            structured_log('warning', 'http.permission_error', method='GET', path=parsed.path, error=str(exc))
            return forbidden(self, str(exc))
        except ValueError as exc:
            structured_log('warning', 'http.value_error', method='GET', path=parsed.path, error=str(exc))
            return bad_request(self, str(exc))
        except Exception as exc:
            structured_log('error', 'http.unhandled_error', method='GET', path=parsed.path, error=str(exc))
            return send_json(self, 500, {'error': str(exc)})

    def do_POST(self):
        parsed = urlparse(self.path)

        try:
            payload = parse_json(self)
        except json.JSONDecodeError:
            return bad_request(self, 'JSON inválido.')
            
        try:
            with closing(get_connection()) as connection:
                company_block_match = re.match(r'^/api/companies/(\d+)/block-status$', parsed.path or '')
                if company_block_match:
                    actor_user_id = resolve_actor_user_id(self, parsed, payload)
                    actor = authorize_action(connection, actor_user_id, 'companies:license')
                    company_id = int(company_block_match.group(1))
                    company = get_company_by_id(connection, company_id)
                    if not company:
                        raise ValueError('Empresa não encontrada.')
                    mark_payment_overdue = str(payload.get('mark_payment_overdue', '')).lower() in ('1', 'true', 'yes', 'on')
                    if mark_payment_overdue and company.get('license_status') != 'suspended':
                        connection.execute("UPDATE companies SET license_status = 'suspended' WHERE id = ?", (company_id,))
                        register_company_audit(
                            connection,
                            company_id,
                            actor,
                            'suspend',
                            'Licença suspensa automaticamente por atraso de pagamento.',
                            [{'field': 'Status da licença', 'before': str(company.get('license_status') or 'active'), 'after': 'suspended'}]
                        )
                        connection.commit()
                    status = evaluate_company_block_status(connection, company_id, persist_expiration=True)
                    return send_json(self, 200, status)

                if parsed.path == '/api/employee-unit-movements':
                    require_fields(payload, ['actor_user_id', 'employee_id', 'target_unit_id', 'movement_type', 'start_date'])
                    actor_user_id = resolve_actor_user_id(self, parsed, payload)
                    actor = authorize_action(connection, actor_user_id, 'employees:update')
                    employee = get_employee_by_id(connection, int(payload['employee_id']))
                    if not employee:
                        raise ValueError('Colaborador não encontrado.')
                    ensure_resource_company(actor, employee, 'Colaborador')
                    target_unit = get_unit_by_id(connection, int(payload['target_unit_id']))
                    if not target_unit:
                        raise ValueError('Unidade de destino não encontrada.')
                    ensure_resource_company(actor, target_unit, 'Unidade de destino')
                    movement_type = str(payload.get('movement_type', '')).strip().lower()
                    if movement_type not in ('temporary', 'definitive'):
                        raise ValueError("Tipo de movimentação inválido. Use 'temporary' ou 'definitive'.")
                    start_date = str(payload.get('start_date', '')).strip()
                    end_date = str(payload.get('end_date', '')).strip()
                    datetime.strptime(start_date, '%Y-%m-%d')
                    if end_date:
                        datetime.strptime(end_date, '%Y-%m-%d')
                        if end_date < start_date:
                            raise ValueError('Data final não pode ser menor que a data inicial.')
                    if movement_type == 'temporary':
                        connection.execute(
                            "UPDATE employee_unit_movements SET end_date = ? WHERE employee_id = ? AND movement_type = 'temporary' AND COALESCE(NULLIF(end_date, ''), '9999-12-31') >= ?",
                            (start_date, employee['id'], start_date)
                        )
                    source_unit_id = int(employee['unit_id'])
                    connection.execute(
                        '''
                        INSERT INTO employee_unit_movements (employee_id, company_id, source_unit_id, target_unit_id, movement_type, start_date, end_date, notes, actor_user_id, actor_name, created_at)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        ''',
                        (
                            employee['id'],
                            employee['company_id'],
                            source_unit_id,
                            int(target_unit['id']),
                            movement_type,
                            start_date,
                            end_date,
                            str(payload.get('notes', '')).strip(),
                            actor['id'],
                            actor['full_name'],
                            datetime.now().isoformat(timespec='seconds')
                        )
                    )
                    if movement_type == 'definitive':
                        connection.execute(
                            'UPDATE employees SET unit_id = ? WHERE id = ?',
                            (int(target_unit['id']), employee['id'])
                        )
                        connection.execute(
                            "UPDATE employee_unit_movements SET end_date = ? WHERE employee_id = ? AND movement_type = 'temporary' AND COALESCE(NULLIF(end_date, ''), '9999-12-31') >= ?",
                            (start_date, employee['id'], start_date)
                        )
                    connection.commit()
                    return send_json(self, 200, {'ok': True})

                if parsed.path == '/api/login':
                    require_fields(payload, ['username', 'password'])
                    payload['username'] = str(payload.get('username', '')).strip()
                    payload['password'] = str(payload.get('password', '')).strip()
                    structured_log('info', 'auth.login_attempt', username=payload['username'])
                else:
                    return not_found(self)

                row = connection.execute(
                    '''
                    SELECT users.id, users.username, users.password, users.full_name, users.role, users.company_id, users.active,
                           companies.name AS company_name, companies.cnpj AS company_cnpj, companies.logo_type
                    FROM users
                    LEFT JOIN companies ON companies.id = users.company_id
                    WHERE users.username = ?
                    ''',
                    (payload['username'],)
                ).fetchone()

                if not row:
                    structured_log('warning', 'auth.login_failed', username=payload['username'], reason='user_not_found')
                    return send_json(self, 401, {'error': 'Usuário não encontrado.', 'code': 'USER_NOT_FOUND'})

                if int(row['active']) != 1:
                    structured_log('warning', 'auth.login_failed', username=payload['username'], user_id=row['id'], reason='user_inactive')
                    return send_json(self, 403, {'error': 'Usuário inativo.', 'code': 'USER_INACTIVE'})

                if not verify_password(row['password'], payload['password']):
                    structured_log('warning', 'auth.login_failed', username=payload['username'], user_id=row['id'], reason='invalid_password')
                    return send_json(self, 401, {'error': 'Senha incorreta.', 'code': 'INVALID_PASSWORD'})

                if not is_bcrypt_hash(row['password']):
                    connection.execute('UPDATE users SET password = ? WHERE id = ?', (hash_password(payload['password']), row['id']))
                    connection.commit()
                if row.get('role') != 'master_admin' and row.get('company_id'):
                    enforce_company_block_rules(connection, int(row['company_id']))

                user_data = row_to_dict(row)
                user_data.pop('password', None)
                structured_log('info', 'auth.login_success', username=row['username'], user_id=row['id'], role=row['role'])

                return send_json(
                    self,
                    200,
                    {
                        'user': user_data,
                        'permissions': sorted(PERMISSIONS.get(row['role'], set())),
                        'token': create_jwt_token(row),
                        'token_expires_in': JWT_EXP_SECONDS
                    }
                )

        except PermissionError as exc:
            structured_log('warning', 'http.permission_error', method='POST', path=parsed.path, error=str(exc))
            return forbidden(self, str(exc))
        except ValueError as exc:
            structured_log('warning', 'http.value_error', method='POST', path=parsed.path, error=str(exc))
            return bad_request(self, str(exc))
        except Exception as exc:
            structured_log('error', 'http.unhandled_error', method='POST', path=parsed.path, error=str(exc))
            return send_json(self, 500, {'error': str(exc)})

    def do_PUT(self):
        parsed = urlparse(self.path)
        try:
            payload = parse_json(self)
            with closing(get_connection()) as connection:
                if parsed.path.startswith('/api/companies/'):
                    company_id = int(parsed.path.rsplit('/', 1)[-1])
                    require_fields(payload, ['actor_user_id', 'name', 'legal_name', 'cnpj', 'plan_name', 'user_limit', 'license_status', 'active'])
                    actor = authorize_action(connection, resolve_actor_user_id(self, parsed, payload), 'companies:update')
                    current = connection.execute('SELECT * FROM companies WHERE id = ?', (company_id,)).fetchone()
                    if not current:
                        raise ValueError('Empresa não encontrada.')
                    previous = row_to_dict(current)
                    payload = validate_company_payload(connection, payload, company_id)
                    connection.execute('UPDATE companies SET name = ?, legal_name = ?, cnpj = ?, logo_type = ?, plan_name = ?, user_limit = ?, license_status = ?, active = ?, commercial_notes = ?, contract_start = ?, contract_end = ?, monthly_value = ?, addendum_enabled = ? WHERE id = ?', (payload['name'], payload['legal_name'], payload['cnpj'], payload['logo_type'], payload['plan_name'], payload['user_limit'], payload['license_status'], int(payload['active']), payload.get('commercial_notes', ''), payload.get('contract_start', ''), payload.get('contract_end', ''), payload.get('monthly_value', 0), payload.get('addendum_enabled', 0), company_id))
                    action_type = 'update'
                    if previous.get('license_status') != 'suspended' and payload.get('license_status') == 'suspended':
                        action_type = 'suspend'
                    elif (previous.get('license_status') in ('suspended', 'expired') or int(previous.get('active', 1)) == 0) and payload.get('license_status') == 'active' and int(payload.get('active', 1)) == 1:
                        action_type = 'reactivate'
                    summary, details = summarize_company_changes(previous, payload)
                    register_company_audit(connection, company_id, actor, action_type, summary, details)
                    connection.commit()
                    return send_json(self, 200, {'ok': True})
                if parsed.path.startswith('/api/users/'):
                    user_id = int(parsed.path.rsplit('/', 1)[-1])
                    require_fields(payload, ['actor_user_id', 'username', 'full_name', 'role'])
                    authorize_user_management(connection, resolve_actor_user_id(self, parsed, payload), 'update', payload['role'], user_id, payload.get('company_id'))
                    current = get_user_by_id(connection, user_id)
                    if not current:
                        raise ValueError('Usuário não encontrado.')
                    incoming_password = str(payload.get('password') or '').strip()
                    if incoming_password:
                        password = hash_password(incoming_password)
                    elif is_bcrypt_hash(current['password']):
                        password = current['password']
                    else:
                        password = hash_password(current['password'])
                    company_id = payload.get('company_id') or None
                    if payload['role'] in ('general_admin', 'admin', 'user') and not company_id:
                        raise ValueError('Perfil com empresa exige uma empresa vinculada.')
                    if company_id and int(payload.get('active', 1)) == 1:
                        ensure_company_user_limit(connection, int(company_id))
                    connection.execute('UPDATE users SET username = ?, password = ?, full_name = ?, role = ?, company_id = ?, active = ? WHERE id = ?', (payload['username'], password, payload['full_name'], payload['role'], company_id, int(payload.get('active', 1)), user_id))
                    connection.commit()
                    return send_json(self, 200, {'ok': True})
                if parsed.path.startswith('/api/units/'):
                    unit_id = int(parsed.path.rsplit('/', 1)[-1])
                    require_fields(payload, ['actor_user_id', 'company_id', 'name', 'unit_type', 'city'])
                    actor = authorize_action(connection, resolve_actor_user_id(self, parsed, payload), 'units:update', int(payload['company_id']))
                    current = get_unit_by_id(connection, unit_id)
                    ensure_resource_company(actor, current, 'Unidade')
                    unit_type = normalize_unit_type(payload.get('unit_type'))
                    connection.execute('UPDATE units SET company_id = ?, name = ?, unit_type = ?, city = ?, notes = ? WHERE id = ?', (payload['company_id'], payload['name'], unit_type, payload['city'], payload.get('notes', ''), unit_id))
                    connection.commit()
                    return send_json(self, 200, {'ok': True})
                if parsed.path.startswith('/api/employees/'):
                    employee_id = int(parsed.path.rsplit('/', 1)[-1])
                    require_fields(payload, ['actor_user_id', 'company_id', 'unit_id', 'employee_id_code', 'name', 'sector', 'role_name', 'admission_date', 'schedule_type'])
                    actor = authorize_action(connection, resolve_actor_user_id(self, parsed, payload), 'employees:update', int(payload['company_id']))
                    current = get_employee_by_id(connection, employee_id)
                    ensure_resource_company(actor, current, 'Colaborador')
                    unit = get_unit_by_id(connection, int(payload['unit_id']))
                    ensure_resource_company(actor, unit, 'Unidade')
                    if str(unit['company_id']) != str(payload['company_id']):
                        raise ValueError('Unidade e empresa do colaborador precisam ser compatíveis.')
                    connection.execute('UPDATE employees SET company_id = ?, unit_id = ?, employee_id_code = ?, name = ?, sector = ?, role_name = ?, admission_date = ?, schedule_type = ? WHERE id = ?', (payload['company_id'], payload['unit_id'], payload['employee_id_code'], payload['name'], payload['sector'], payload['role_name'], payload['admission_date'], payload['schedule_type'], employee_id))
                    connection.commit()
                    return send_json(self, 200, {'ok': True})
                if parsed.path.startswith('/api/epis/'):
                    epi_id = int(parsed.path.rsplit('/', 1)[-1])
                    require_fields(payload, ['actor_user_id', 'company_id', 'unit_id', 'name', 'purchase_code', 'ca', 'sector', 'stock', 'unit_measure', 'ca_expiry', 'epi_validity_date', 'manufacture_date', 'validity_days'])
                    actor = authorize_action(connection, resolve_actor_user_id(self, parsed, payload), 'epis:update', int(payload['company_id']))
                    current = get_epi_by_id(connection, epi_id)
                    ensure_resource_company(actor, current, 'EPI')
                    unit = get_unit_by_id(connection, int(payload['unit_id']))
                    ensure_resource_company(actor, unit, 'Unidade')
                    if str(unit['company_id']) != str(payload['company_id']):
                        raise ValueError('Unidade e empresa do EPI precisam ser compatíveis.')
                    payload['qr_code_value'] = (payload.get('qr_code_value') or generate_epi_qr_code(payload)).strip()
                    connection.execute('UPDATE epis SET company_id = ?, unit_id = ?, name = ?, purchase_code = ?, ca = ?, sector = ?, stock = ?, unit_measure = ?, ca_expiry = ?, epi_validity_date = ?, manufacture_date = ?, validity_days = ?, qr_code_value = ? WHERE id = ?', (payload['company_id'], payload['unit_id'], payload['name'], payload['purchase_code'], payload['ca'], payload['sector'], int(payload['stock']), payload['unit_measure'], payload['ca_expiry'], payload['epi_validity_date'], payload['manufacture_date'], int(payload['validity_days']), payload['qr_code_value'], epi_id))
                    connection.commit()
                    return send_json(self, 200, {'ok': True})
            return not_found(self)
        except PermissionError as exc:
            structured_log('warning', 'http.permission_error', method='PUT', path=parsed.path, error=str(exc))
            return forbidden(self, str(exc))
        except ValueError as exc:
            structured_log('warning', 'http.value_error', method='PUT', path=parsed.path, error=str(exc))
            return bad_request(self, str(exc))
        except DBIntegrityError as exc:
            structured_log('warning', 'http.integrity_error', method='PUT', path=parsed.path, error=str(exc))
            return bad_request(self, f'Erro de integridade: {exc}')

    def do_DELETE(self):
        parsed = urlparse(self.path)
        try:
            with closing(get_connection()) as connection:
                if parsed.path.startswith('/api/users/'):
                    user_id = int(parsed.path.rsplit('/', 1)[-1].split('?')[0])
                    actor_user_id = resolve_actor_user_id(self, parsed)
                    authorize_user_management(connection, actor_user_id, 'delete', None, user_id, None)
                    if actor_user_id == user_id:
                        raise ValueError('Não é permitido excluir o próprio usuário logado.')
                    connection.execute('DELETE FROM users WHERE id = ?', (user_id,))
                    connection.commit()
                    return send_json(self, 200, {'ok': True})
                if parsed.path.startswith('/api/units/'):
                    unit_id = int(parsed.path.rsplit('/', 1)[-1].split('?')[0])
                    actor = authorize_action(connection, resolve_actor_user_id(self, parsed), 'units:delete')
                    unit = get_unit_by_id(connection, unit_id)
                    ensure_resource_company(actor, unit, 'Unidade')
                    if connection.execute('SELECT COUNT(*) FROM employees WHERE unit_id = ?', (unit_id,)).fetchone()[0]:
                        raise ValueError('Não é possível excluir unidade com colaboradores vinculados.')
                    connection.execute('DELETE FROM units WHERE id = ?', (unit_id,))
                    connection.commit()
                    return send_json(self, 200, {'ok': True})
                if parsed.path.startswith('/api/employees/'):
                    employee_id = int(parsed.path.rsplit('/', 1)[-1].split('?')[0])
                    actor = authorize_action(connection, resolve_actor_user_id(self, parsed), 'employees:delete')
                    employee = get_employee_by_id(connection, employee_id)
                    ensure_resource_company(actor, employee, 'Colaborador')
                    if connection.execute('SELECT COUNT(*) FROM deliveries WHERE employee_id = ?', (employee_id,)).fetchone()[0]:
                        raise ValueError('Não é possível excluir colaborador com ficha registrada.')
                    connection.execute('DELETE FROM employees WHERE id = ?', (employee_id,))
                    connection.commit()
                    return send_json(self, 200, {'ok': True})
                if parsed.path.startswith('/api/epis/'):
                    epi_id = int(parsed.path.rsplit('/', 1)[-1].split('?')[0])
                    actor = authorize_action(connection, resolve_actor_user_id(self, parsed), 'epis:delete')
                    epi = get_epi_by_id(connection, epi_id)
                    ensure_resource_company(actor, epi, 'EPI')
                    if connection.execute('SELECT COUNT(*) FROM deliveries WHERE epi_id = ?', (epi_id,)).fetchone()[0]:
                        raise ValueError('Não é possível excluir EPI com ficha registrada.')
                    connection.execute('DELETE FROM epis WHERE id = ?', (epi_id,))
                    connection.commit()
                    return send_json(self, 200, {'ok': True})
            return not_found(self)
        except PermissionError as exc:
            structured_log('warning', 'http.permission_error', method='DELETE', path=parsed.path, error=str(exc))
            return forbidden(self, str(exc))
        except ValueError as exc:
            structured_log('warning', 'http.value_error', method='DELETE', path=parsed.path, error=str(exc))
            return bad_request(self, str(exc))


if __name__ == '__main__':
    bootstrap_admin = init_db()
    port = int(os.environ.get('EPI_PORT', os.environ.get('PORT', '8000')))
    server = ThreadingHTTPServer(('0.0.0.0', port), EpiHandler)
    structured_log(
        'info',
        'auth.config',
        bcrypt_available=BCRYPT_AVAILABLE,
        jwt_exp_seconds=JWT_EXP_SECONDS,
        jwt_secret_default=JWT_SECRET == 'change-this-jwt-secret',
        password_recovery_key_configured=bool(PASSWORD_RECOVERY_KEY)
    )
    if bootstrap_admin:
        structured_log('info', 'bootstrap.completed', user_id=bootstrap_admin.get('id'), username=bootstrap_admin.get('username'))
    structured_log('info', 'server.started', port=port)
    server.serve_forever()
