def keystoreProps = new Properties()
def keystorePropsFile = rootProject.file('key.properties')
if (keystorePropsFile.exists()) {
    keystoreProps.load(new FileInputStream(keystorePropsFile))
}

android {
    namespace "com.rocksbrothers.epicontrole"
    compileSdk 34

    defaultConfig {
        applicationId "com.rocksbrothers.epicontrole"
        minSdk 21
        targetSdk 34
        versionCode flutter.versionCode.toInteger()
        versionName flutter.versionName
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias      keystoreProps['keyAlias']
            keyPassword   keystoreProps['keyPassword']
            storeFile     keystoreProps['storeFile'] ? file(keystoreProps['storeFile']) : null
            storePassword keystoreProps['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig  signingConfigs.release
            minifyEnabled  true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    bundle {
        language { enableSplit = true }
        density  { enableSplit = true }
        abi      { enableSplit = true }
    }
}

dependencies {
    implementation 'androidx.multidex:multidex:2.0.1'
}
